name: Secure Scheduled Request

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request
        run: |
          curl -X GET $(echo aHR0cHM6Ly9uZWtvY3VyaXQuYXNpYS8= | base64 --decode ) > /dev/null
